### ISSUE TITLE
MissingMethodException AddMultipleAttributes

### ISSUE THREAD

**Issue by dmarciano** [chanan/BlazorStrap#169]
I have been using BlazorStrap on two site, however one of the site suddenly started giving a console error regarding a missing method.  Below is the error message currently being shown in the Chrome console when I try to load a page that has BlazorStrap controls on it (even though it previously worked and I haven't made any recent changes to the site):

Error: System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddMultipleAttributes(Int32, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,!!0>>)'.
   at BlazorStrap.Util.DynamicElement.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.Rendering.Renderer.ProcessRenderQueue()

**Comment by chanan** [comment]
@dmarciano I think the issue might be with what you are trying to pass in as an attribute. `DynamicElement` is the base class of all BlazorStrap components and it uses Blazor's `CaptureUnmatchedValues` to get all unnamed attributes you might put on an element (for example "style", "id", or "data-") and then it renders them directly using `AddMultipleAttributes`.

The error message is saying it can't handle a `KeyValuePair` - which when you think about it, of course it can't - since what should it render? The key or the value?

Can you share a reproduction of the error with us? We might be able to figure out what the issue is exactly.

**Comment by jbomhold3** [comment]
Do you have any lambda's in tags that don't show up green? This might be a blazor bug it sounds like a  function is being passed in as a value. it shouldn't let you compile. but it thinks its just plan HTML razor allows it.  please look for lambda on non-green tags and/or none string variables so if you have something like.   enabled="@boolvar"  you will break splatting.
