### ISSUE TITLE
Need a build for Blazor 0.6.0 release

### ISSUE THREAD

**Issue by MarkStega** [chanan/BlazorStrap#18]
Running an app on 0.6.0 with BlazorStrap 0.5.1 does not work well. I simply cloned the repository and built BlazorStrap locally against 0.6.0; no changes were needed and everything seems to function.

**Comment by chanan** [comment]
Thanks! Will update tonight, so you should have a fresh build tomorrow morning. 

After the initial release to 0.6.0 will look into templates, I am sure they will help in many places

**Comment by MarkStega** [comment]
Thanks, any thoughts on issue #13 ?

**Comment by chanan** [comment]
No, sorry neglacted the project for a bit because so many other things broke with Blazor 0.5.0 (my other projects more then this one). I will try to find a solution once its updated to Blazor 0.6 - worse comes to worse, if IsDisabled, it can always be rendered as a non link with the same styles. Maybe...

**Comment by chanan** [comment]
Updated, should be on nuget shortly.
