### ISSUE TITLE
TabPane

### ISSUE THREAD

**Issue by simonziegler** [chanan/BlazorStrap#2]
Hi Chanan,

Thanks for your Blazorstrap work! I've just started trying it out, and am struggling to find a tab pane example for Navs. Is there one you can refer me to please?

Many thanks,  Simon

**Comment by chanan** [comment]
Sample added
web page: https://chanan.github.io/BlazorStrap/tabs.html
Code page: https://github.com/chanan/BlazorStrap/blob/master/src/Sample/Pages/Tabs.cshtml

Things to note:

1. Syntax isn't great, but till Blazor supports the concept of context it will have to do
2. The navs aren't colored in blue and the cursor doesn't change to a "hand" this is because in plain html/bootstrap they get the class from href="#", however in Blazor, if you do that the click will be captured by the link and there is no way to prevent that. I have a bug opened in the Blazor repo for that.
