### ISSUE TITLE
BSBasicInput Binding Issue

### ISSUE THREAD

**Issue by endeffects** [chanan/BlazorStrap#206]
I'm using the BSBasicInput to bind my models to a form. I've noticed that is currently not possible to bind anything else than strings and the generic support for other data types is available for BSInput components with an EditContext only.

Due the reason that i'm using a custom validation i can not use this, that why i'd to ask you to allow generic bindings for basic inputs too.

**Comment by jbomhold3** [comment]
It forces the user to supply a binding because of type of T. So we opted for basic to be used as an ill handle everything but the UI case. Still working on figuring if it's posable to do a default generic type.  If I can do that I will be more then happy to provide generic bindings for basic input. You can pass an editcontext that you don't use and use the bsinput.  If you have any ideas to default a generic let me know. This is something I really want to add to BSBasicInput

**Comment by jbomhold3** [comment]
Think I have something that will work testing now

**Comment by jbomhold3** [comment]
@bind-value="foo" or value="foo"  is now required on BSBasicInput. However, binding to type T is now allowed.

**Comment by jbomhold3** [comment]
Released

**Comment by endeffects** [comment]
Thanks alot, the generic binding works now. :)
