### ISSUE TITLE
How to remove class from BSNavbar

### ISSUE THREAD

**Issue by vixisoft** [chanan/BlazorStrap#214]
I want to use the BSNavbar but it is adding navbar-light or navbar-dark.

I dont want to use them, so how is it possible to remove them ?
I think we should not have to create an jsinteropt to remove class from a framework.

**Comment by chanan** [comment]
Hi @vixisoft ,

Looking at the examples on the bootstrap site: https://getbootstrap.com/docs/4.3/components/navbar/ it seems that navrbar always has navbar-light. What is your use case that it needs to be removed?

Also you do have 2 quick options to get around the navbar-light:

1. You could simply use a div styled the way you want it instead of BSNavBar:

```
<div class="navbar">
  <!-- Other BlazorStrap controls go here -->
</div>
```

2. Each BlazorStrap control supports `style` and `Class` - note that Class is capitalized, which will get applied to the control. Specifically, `Class` will get applied at the end of the class string of the div, so you can use it to supply a class and override any CSS that gets applied by Bootstrap.

**Comment by jbomhold3** [comment]
I'm guessing they are using a template that does not override it.

If we change

https://github.com/chanan/BlazorStrap/blob/3bdee604e8481812cb2a49a2abae43b7866ae9b8/src/BlazorStrap/Components/Nav/BSNavbar.razor.cs#L39

.AddClass("navbar-light", !IsDark &&  Color != Color.None)

It would allow removing it by setting the color to none.

**Comment by jbomhold3** [comment]
Added bool **HideLight**
