### ISSUE TITLE
Internet Explorer 11 error

### ISSUE THREAD

**Issue by daparici** [chanan/BlazorStrap#282]
JavaScript critical error at line 115, column 22 in https://localhost:44392/_content/BlazorStrap/blazorStrap.js\n\nSCRIPT1003: ':' was expected

**Comment by chanan** [comment]
IE 11 didnt support shorthand json notation? Seems odd.

```
{
   placement,
   .... More json
}
```

I will change it to the expanded version next release. I am not sure I can easily test it out though.

**Comment by arivera12** [comment]
@chanan I hit this bug on 2017 and yes IE11 doesn't support shorthand json notation. I hope and wish IE dies soon. IE11 its being slowly replaced by Edge, since edge started it supports shorthand json notation and many js stuff and a lot of others css rules not supported in IE11. Edge latest version is using chromium engine by now since january of this year. It's just a matter of time.
![image](https://user-images.githubusercontent.com/5600102/79053522-16ab5380-7c0c-11ea-8d57-643553d91672.png)

**Comment by chanan** [comment]
Fixed. will be in next release
