### ISSUE TITLE
Reset button behaves different to submit button

### ISSUE THREAD

**Issue by jaldinger** [chanan/BlazorStrap#291]
The **reset** button seems to take the caption from the "Value" tag, whereas the **submit** button takes the caption from the content.
See definition:
![image](https://user-images.githubusercontent.com/20828844/79282336-ecaf9680-7e82-11ea-8b0b-1c01ae4b356e.png)

And result:
![image](https://user-images.githubusercontent.com/20828844/79282292-d30e4f00-7e82-11ea-85ca-4c81a24c6b17.png)

Or am I looking at this the wrong way?

**Comment by chanan** [comment]
It is possible that there is no way to fix this.

When `ButtonType.Submit`, the tag gets rendered as a `<button>`.
When `ButtonType.Reset`, the tag gets rendered as `<input>` 

That is because reset needs to actually reset the values so it needs be an `input` tag which in turn takes its text from the value attribute. 

Off hand I am not sure how we can change this to match the behaviors.

**Comment by jaldinger** [comment]
OK. I understand. It's not a big deal since it's easy to take care off, but since I didn't find any other question or issue about this, I still wanted to raise it.
