### ISSUE TITLE
Update Documentation on website

### ISSUE THREAD

**Issue by Serge-N** [chanan/BlazorStrap#346]
https://blazorstrap.io/themes needs to be corrected Client Side on the second title needs to be Server Side. Startup.cs changed to Program.cs . Also there is need to clarify on the home page, that  await BootstrapCss.SetBootstrapCss("4.3.1"); needs to be called in OnInitializedAsync() and not OnInitAsync() according to https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1

**Comment by chucker** [comment]
See #348 and #349. Both the README and the docs can use improvement.

As for the **Themes** page, that's a bit misleading. I'd say the entire setup stuff doesn't belong there any more; instead, unify that at the **Home** page. The Themes page should focus on how to use the feature, not how to set it up (because that gives the misleading impression that it describes how to set up _all_ of BlazorStrap).
