### ISSUE TITLE
Bootstrap v5 alpha: how do we support it?

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStrap#361]
Bootstrap v5 alpha is out...

**Comment by jbomhold3** [comment]
We can branch and start dev with .net 5 previews and just roll it up when people goto .net 5

**Comment by MasterSkriptor** [comment]
I agree @jbomhold3. We should make a new branch for v5. 

Another cool thing would be to allow different html tags for the bootstrap components that support it. For example, using the nav tag with a tags instead of the ul tag with li for BSNav, etc.

The more robust and html5 compliant our components render the more useful the framework is.

The trick is to give as much control to the developers as they want while keeping it simple enough for beginners to learn.

Another awesome thing would be to have templates for vs that prebake blazor strap into wasm and server side blazor projects.

**Comment by MasterSkriptor** [comment]
We should probably develop Bootstrap 5 using .Net 5 as well.

**Comment by chucker** [comment]
> IG having something like <BSDiv Class="COL-SM-7 | COL-MD-5 | COL-LG-3"> add the classes based on flags for simple layout features.

Do you mean something like @egil's tech demo? https://github.com/egil/bootstrap.net

**Comment by egil** [comment]
> > IG having something like <BSDiv Class="COL-SM-7 | COL-MD-5 | COL-LG-3"> add the classes based on flags for simple layout features.
> 
> Do you mean something like @egil's tech demo? https://github.com/egil/bootstrap.net
> 
> 

Ahh memories. If you are going with breaking changes, I have a another suggestion which will save your users lots of typing: making subcomponents render tree change depending on the context they are used in. E.g. `a` inside an `alert` automatically gets the `.alert-link` class, and `h1-6` automatically gets the `.alert-header` class.

Let me know if you want to learn more about this approach. It's also used in the dev branch of that repo @chucker linked to.

**Comment by egil** [comment]
Making components context sensitive also means you can remove unneeded components that users have to type out. E.g. the `breadcrumb` component could just have look like this when used:

```
<Breadcrumb>
  <A href="/">Home</A> <A href="/docs/4.3/">Documentation</A>
  <A href="/docs/4.3/components">Components</A>
  <A href="/docs/4.3/components/breadcrumbs">Breadcrumbs</A>
</Breadcrumb>
```

No need to wrap `a` inside `breadcrumpitem` components. 

In general, consider not mirroring bootstraps HTML structure completely unless needed. Sometimes their components have addition `div` tags that are there for willing purposes, that your library can add automatically for the user.

**Comment by NPadrutt** [comment]
Hi, I stumbled over this and wondered if bootstrap 5 is supported in the meanwhile or if there is still work to be done?

**Comment by kayceebalintong** [comment]
Was wondering this myself 😬😬
