### ISSUE TITLE
Unexpected BSCarousel implementation details

### ISSUE THREAD

**Issue by mark-at-tusksoft** [chanan/BlazorStrap#379]
Splitting this off from my post on the docs #378 as the following is specific to the source.

I'm still pretty new to Blazor but is there no way to make only `BSCarousel` concerned with `NumberOfItems`? Why are some of the child `BSCarousel*` components requiring the same parameter to be provided instead of deferring to the parent after some Post-Initialization call? (same for Interval on items, seems they always have a default value which resets the interval on `ResetTimer()` causing the BSCarousel's Interval to become ignored)

Also, why does `BSCarouselItem` assume an image? I am using it for generic html slides which results in an empty img tag in all my slides. Might make sense to have `BSCarouselItem` not consider images at all and derive a `BSCarouselImageItem` as a convenience component, just spitballing.

I can't seem to get the clickable elements in `<BSCarouselIndicators NumberOfItems="3" />`  to work. They don't work in the samples for me either. No exceptions, just seems they aren't wired up, not sure what the expected usage is here.

Another issue I noticed, BSCarousel.OnMouseLeave() appears to get called before the CarouselItem children finish initializing which causes an exception to get thrown when BSCarousel.ResetTimer() is called because it tries to element-access an empty list.

**Comment by MasterSkriptor** [comment]
I'll take a look at this.

**Comment by MasterSkriptor** [comment]
As I mentioned in #378, all of the samples are working for me in both chromium edge, and chrome. What browser are you using, and what version?

**Comment by MasterSkriptor** [comment]
I cant speak for the one who wrote the code in BSCarouselControl, but I have some theories and opinions on why it has its own NumberOfItems property. First, the NumberOfItem passed into BSCarousel, BSCarouselIndicators, and BSCarouselControl, is meant to be passed into the controls via the Code Block. This should increase performance because each of the controls has a static version of the count, without having to get it from the parent CascadingParameter. It also would allow you to add a cover slide that would not end up in the rotation if you wanted to do that.

It should be noted that this issue could easily be solved by using the BSDataCarousel and passing in the items list. It also makes creating the Carousel much more concise, with less code.

To get back to the main point, I am not getting the errors you are mentioning. It would be helpful for troubleshooting if you could let me know what browser you are using, and the version.

**Comment by chanan** [comment]
Since I did write, I can easily answer that :)

This project was written back in when the very first preview of Blazor came out, and many techniques that work now didn't work back then, for example cascading parameters didn't exist back then.

If there is something that could be updated to make life easier now, then lets do it! (@mark-at-tusksoft PRs are always welcome ;) )

**Comment by MasterSkriptor** [comment]
I think it is still relevant because of performance (not using the CascadingParameter, and for the ability to control the number of items, so that you can ignore a cover slide if you wish. (I havent tried to do that, so I'm running the risk of sounding dumb. But I think you can add a slide before the for loop and it not be included in the previous and next buttons.) Also, it is just as easy to use the BSDataCarousel to accomplish the same thing if you dont need that much control.

**Comment by chanan** [comment]
Sorry, I mentioned Cascading Parameters as an example, not as an implementation. We should do what makes sense of course
