### ISSUE TITLE
v5 BSInputCheckbox always returns CheckedValue in ValueChangedEvent

### ISSUE THREAD

**Issue by MikePrime21** [chanan/BlazorStrap#471]
I'm using the 5.0 version to bind a checkbox using the switch css class.  No matter what I do, the CheckedValue is always passed into the ValueChanged event.  .  

```
<div Class="@BS.Form_Check @BS.Form_Switch @BS.Float_End">
    <BSLabel IsCheckLabel="true">Is Active</BSLabel>
    <BSInputCheckbox T="@bool" CheckedValue="true" UnCheckedValue="false" Value="@IsActive" ValueExpression="@(() => IsActive)" ValueChanged="@((bool e) => OnActiveChanged(e))" />
</div>
```

**Comment by jbomhold3** [comment]
Able to reproduce it working the issue now.

**Comment by jbomhold3** [comment]
Found the issue. Pushed RC3 with the fix. Since this is broken basic behavior. 
Just a note T="@bool" is not needed it can get it's type from the Value.

https://www.nuget.org/packages/BlazorStrap/5.0.0-RC-3
Also your probably doing this already but. Make sure however since you're not doing @bind-Value you're setting the value back to `IsActive` from the Event Callback shown below.
``` C#
 private void OnActiveChanged(bool e)
{
      IsActive = e;
}
```
