### ISSUE TITLE
Problem with documentation

### ISSUE THREAD

**Issue by obriankevin11** [chanan/BlazorStrap#564]
Hi,

I'm trying to use BsDataTable / Data Table Example using FetchData (https://blazorstrap.io/V5/V5/content/tables or https://blazorstrap.io/V5/content/tables, website is experiencing issues while I'm writing this issue).

It looks to me that the documentation is missing some information.

```
<BSDataTable FetchItems="FetchItems" PaginationBottom="true" StartPage="_startPage" RowsPerPage="20" Context="item">
    <Header>
        <BSDataTableHead TValue="Employee" Sortable="true" Column="@(nameof(Employee.Id))">Id</BSDataTableHead>
        <BSDataTableHead TValue="Employee" Sortable="true" Column="@(nameof(Employee.Name))" ColumnFilter="true">Name</BSDataTableHead>
        <BSDataTableHead TValue="Employee" Sortable="true" Column="@(nameof(Employee.Email))" ColumnFilter="true">Email</BSDataTableHead>
    </Header>
```

There is nothing regarding Employee which should be a class. And is used as a type while it is a class (Column="@(nameof(Employee.Id))").

No documentation also about Table2Model.

` private readonly Table2Model _model = new Table2Model();`

Thank you for your help!

**Comment by jbomhold3** [comment]
I'm confused about what you're looking for with this question. If it's just reporting model that isn't shown in the example. It's was not really the focus of the example so not shown. However, if it's confusing because it's missing I can add it to the docs.

Files are below 
https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap-Docs/SampleModels/Content/Tables/Employee.cs
https://github.com/chanan/BlazorStrap/blob/master/src/BlazorStrap-Docs/SampleModels/Content/Tables/Table2Model.cs

**Comment by obriankevin11** [comment]
Thanks! I was confused by "Dataset" property type which I thought was a System.Data.DataSet. Thanks for providing the files and clarification!
