### ISSUE TITLE
Support Blazor Preview 6

### ISSUE THREAD

**Issue by IvanJosipovic** [chanan/BlazorStrap#58]
Preview 6 added quite a few breaking changes.

Blog: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-6/

**Comment by chucker** [comment]
This is a bit tricky and messy.

* There's a lot of copy & paste-style syntax changes. Easy to get some of this wrong, especially since BlazorStrap has code samples, which _also_ need replacing.
* Some of the syntax will actually change even further later on. In preview 6, you need to write `@onclick="@Clicked"` instead of `onclick="@Clicked"` (and we _must_ change that). But in future previews, it will be `@onclick="Clicked"`. (It's not entirely clear to me if both will be supported.)
* VS's tooling gets confused by some of the new syntax. It doesn't recognize `@code` correctly.

**Comment by chanan** [comment]
@chucker I started for a simpler Blazor project I have which is just a logger wrapper that I use in BlazorDB last night. Once that is done, I will start on BlazorStrap. It didnt seem too bad, Search & Replace got most of it.
