### ISSUE TITLE
Prevent Modal from closing when clicking outside or escape

### ISSUE THREAD

**Issue by aherrick** [chanan/BlazorStrap#81]
Can this be a first class option? I want the modal to be always there until a user cancels or clicks ok.

https://www.tutorialrepublic.com/faq/how-to-prevent-bootstrap-modal-from-closing-when-clicking-outside.php

**Comment by chanan** [comment]
Well the good news is, I never got Esc key working... 

Using the code from the link above won't work out of the box as it is calling bootstrap js which is not used by BlazorStrap. However, what we can do, is to run the code from that link and see what it actually does, then translate that to what we need to do to provide the same functionality.

If you are interested in doing that and submitting a PR let me know, otherwise I can do it.

**Comment by chanan** [comment]
Ignore that, I am adding that in the release that is going out shortly

**Comment by chanan** [comment]
Added in 1.0.0-preview6-14

**Comment by chanan** [comment]
@jbomhold3 fixed closing a modal using the Escape key and added IgnoreEscape param in 1.0.0-preview6-15
